// APP

// Profile
const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const SIGNUP = 'SIGNUP';
const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
const UPDATE_PROFILE = 'UPDATE_PROFILE';

export {LOGIN, SIGNUP, LOGOUT, UPDATE_PROFILE, FORGOT_PASSWORD};
